</$objtype/mkfile

LIB=/$objtype/lib/libann.a

OFILES=\
	ann.$O\
	annrun.$O\
	anntrain.$O\
	anncreate.$O\
	weightsinit.$O\
	anntrain_adam.$O\
	anntrain_adamax.$O\

HFILES=\
	/sys/include/ann.h\

</sys/src/cmd/mksyslib
